// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function make(title, message) {
  return React.createElement("div", {
              className: "banner"
            }, React.createElement("h2", undefined, title), message);
}

export {
  make ,
  
}
/* react Not a pure module */
